
version: '3.8'

services:
  fes-app:
    build: .
    container_name: fes_project
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - database
    command: python src/main.py

  database:
    image: postgres:13
    container_name: fes_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
