[project]
name = "repl-nix-fluctuationintelligence"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "astroid>=3.3.8",
    "flask>=3.1.0",
    "numpy>=2.2.1",
    "pylint>=3.3.3",
    "pytest>=8.3.4",
    "scipy>=1.14.1",
]
