
version: '3.9'
services:
  biohub-backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/biohub
      NODE_ENV: production
      FEATURE_FLAGS: biosafety,biostasis,iot_monitoring,outbreaks,incidents
    depends_on:
      - mongo

  biohub-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
