
services:
  kafka:
    broker: "localhost:9092"
    replication_factor: 3
    topics:
      - name: "sensor_data"
        partitions: 3

  influxdb:
    host: "localhost"
    port: 8086
    database: "fes_data"
    retention_policy: "autogen"

  ipfs:
    host: "localhost"
    port: 5001
    cluster: true
    replication_factor: 2

  immudb:
    host: "localhost"
    port: 3322
    database: "immutable_logs"

  redis:
    host: "localhost"
    port: 6379
    password: "securepassword"

security:
  zero_trust: true
  quantum_safe:
    enabled: true
    qkd_key_exchange: "active"
    pqc_algorithm: "kyber"
